### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Or1j1n** [gbl/GrabcraftLitematic#3]
Hi,

Love the idea behind this mod, sadly i can't make it work.

I got this issue when trying to import this URL : https://www.grabcraft.com/minecraft/tauren-totem/towers#general

![ssl error](https://user-images.githubusercontent.com/8409935/98994033-87627780-252f-11eb-858a-4fe063630571.png)

Any idéa ?

**Comment by gbl** [comment]
This is a problem with old java versions (like the one that comes with Minecraft) not understanding the security certificate that's used by GrabCraft. Please try version 0.3 of the mod; it says it's for 1.16.4 but should work from 1.16.2 on. That version has a hack that adds the certificate even to older java versions.

**Comment by Or1j1n** [comment]
ok will do, thx
