### ISSUE TITLE
 Problem with URL: sun.security.validator.ValidatorException

### ISSUE THREAD

**Issue by Zano1999** [gbl/GrabcraftLitematic#4]
I have this error when i try to download a structure:
Problem with URL: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification to requested target

I use:
Litematica: litematica-fabric-1.16.4-0.0.0-dev.20201103.184101
Grabcraft: grabcraft-litematic-1.16.4-fabric0.25.1-0.3
Fabric API: fabric-api-0.25.1+build.416-1.16
Fabric Loader: fabric-loader-0.10.8-1.16.4

**Comment by gbl** [comment]
This should be fixed in the 0.3 version - please upload a **complete** client log somewhere so I can check it for possible errors.

**Comment by Zano1999** [comment]
Here the latest log (after clicking on download):
https://pastebin.com/wCwaYeYP

**Comment by gbl** [comment]
I just put ab a release here on github (https://github.com/gbl/GrabcraftLitematic/releases/tag/0.3.1) that should *hopefully* fix the problem - could you please check it?

There should be, very early in the log file, an entry similar to that (version 0.3.1, not yours):

```
[07:03:10] [main/INFO]: Grabcraft-Litematic merging cacerts
[07:03:10] [main/INFO]: - seems to have worked ok
[07:03:12] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
```
If you still get the PKIX error, this (or the possible error message) is what I'd be particularily interested in.

**Comment by Zano1999** [comment]
It finally works, thanks alot 😃
